### ISSUE TITLE
Dependency problems since Conda update

### ISSUE THREAD

**Issue by nenadmacesic** [wtmatlock/flanker#50]
Hi,

I've previously used Flanker without issues but recently had to re-install it. Since then I have kept having the same error message despite running the same commands that worked successfully previously. Any tips much appreciated:

Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/flanker/bin/flanker", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/miniconda3/envs/flanker/lib/python3.7/site-packages/flanker/flanker.py", line 618, in main
    flanker_main()
  File "/home/ubuntu/miniconda3/envs/flanker/lib/python3.7/site-packages/flanker/flanker.py", line 570, in flanker_main
    args.fasta_file, args.window, gene.strip())
  File "/home/ubuntu/miniconda3/envs/flanker/lib/python3.7/site-packages/flanker/flanker.py", line 421, in flank_fasta_file_lin
    data = pd.read_csv(unfiltered_abricate_file, sep='\t', header=0)
  File "/home/ubuntu/miniconda3/envs/flanker/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/flanker/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/ubuntu/miniconda3/envs/flanker/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/ubuntu/miniconda3/envs/flanker/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/ubuntu/miniconda3/envs/flanker/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/ubuntu/miniconda3/envs/flanker/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 69, in __init__
    self._reader = parsers.TextReader(self.handles.handle, **kwds)
  File "pandas/_libs/parsers.pyx", line 549, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file

**Comment by nenadmacesic** [comment]
Hi - this problem was solved by updating Abricate to the current version but then issues with Mash emerged. Is it possible that updating Conda has affected things?

**Comment by nenadmacesic** [comment]
Hi - this problem was solved by troubleshooting things in Abricate. It looks like a problem with the version of BLAST used with Abricate. Please see here for full details:
https://github.com/tseemann/abricate/issues/164

**Comment by bede** [comment]
Hi @nenadmacesic, thank you for reporting your experience. Were you able to fix this issue using `abricate --setupdb`?

Do you think we should be pinning a specific version of Abricate and/or BLAST?
